#  this is task menu
tasks:
  - name : bash1
    init :  bash install.sh
    command : cd backend && nodemon index.js
  - name : bash2
    init : cd prenotebook
    command : npm install

ports:
  - port: 3002
    # onOpen: open-preview
