#  this is task menu
tasks:
  - name : Terminal 1
    before : code --install-extension "/workspace/PreNotebook/z-comp/formulahendry.auto-rename-tag-0.1.8.vsix" "/workspace/PreNotebook/z-comp/rangav.vscode-thunder-client-1.9.0.vsix"
    init : cd backend && npm i && npm install -g -D nodemon 
    command : nodemon index.js
  - name : Terminal 2
    before : cd prenotebook
    init : npm i
    command : echo "Inside the frontend"

ports:
  - port: 3002
    onOpen: open-preview
